[package]
name = "alloy_helper"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
alloy-primitives = { version = "0.8.15" }