[package]
name = "cli"
description.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "reakula"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
tokio.workspace = true
eyre.workspace = true